"""retirando o campo cache hit da tabela route_access_log

Revision ID: 2a0a4b153976
Revises: a9106612b2c8
Create Date: 2026-01-11 18:57:52.096564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0a4b153976'
down_revision: Union[str, Sequence[str], None] = 'a9106612b2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_access_log', 'cache_hit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_access_log', sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
