"""Criando nova coluna de refresh_token

Revision ID: 37c2ee013856
Revises: 87c19c5bb880
Create Date: 2025-12-04 20:47:58.545932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c2ee013856'
down_revision: Union[str, Sequence[str], None] = '87c19c5bb880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_acess', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_acess', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
