"""Adicionando coluna model useraccess refresh_token_expire_at

Revision ID: 489af00c05e6
Revises: cf02abf0a57a
Create Date: 2025-12-04 22:51:04.167942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489af00c05e6'
down_revision: Union[str, Sequence[str], None] = 'cf02abf0a57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_acess', sa.Column('refresh_token_expire_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_acess', 'refresh_token_expire_at')
    # ### end Alembic commands ###
