"""ADudicionando nova coluna de refresh_token no model de userAccess

Revision ID: 87c19c5bb880
Revises: 53f0fea14c7e
Create Date: 2025-12-04 20:39:29.223659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c19c5bb880'
down_revision: Union[str, Sequence[str], None] = '53f0fea14c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_acess', sa.Column('refresh_token', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_acess', 'refresh_token')
    # ### end Alembic commands ###
