"""adicionando_metricas_de_performance_no_route_access_log

Revision ID: a9106612b2c8
Revises: 2d95939272e0
Create Date: 2026-01-11 17:35:09.642849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9106612b2c8'
down_revision: Union[str, Sequence[str], None] = '2d95939272e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_access_log', sa.Column('response_time_ms', sa.Float(), nullable=True))
    op.add_column('route_access_log', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('route_access_log', sa.Column('cache_hit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_access_log', 'cache_hit')
    op.drop_column('route_access_log', 'status_code')
    op.drop_column('route_access_log', 'response_time_ms')
    # ### end Alembic commands ###
