"""removend columns token

Revision ID: cf02abf0a57a
Revises: 37c2ee013856
Create Date: 2025-12-04 22:44:04.949255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf02abf0a57a'
down_revision: Union[str, Sequence[str], None] = '37c2ee013856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_acess', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_acess', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
