"""Adicionando e renomeando novos campos no model books recommendation

Revision ID: d2bccf40b294
Revises: 6292681dfe0b
Create Date: 2025-12-18 22:17:58.111202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bccf40b294'
down_revision: Union[str, Sequence[str], None] = '6292681dfe0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_recommendation', sa.Column('inputed_book_id', sa.Integer(), nullable=True))
    op.add_column('book_recommendation', sa.Column('inputed_book_title', sa.String(length=500), nullable=False))
    op.add_column('book_recommendation', sa.Column('recommended_book_title', sa.String(length=500), nullable=False))
    op.drop_column('book_recommendation', 'original_book_id')
    op.drop_column('book_recommendation', 'original_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_recommendation', sa.Column('original_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('book_recommendation', sa.Column('original_book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('book_recommendation', 'recommended_book_title')
    op.drop_column('book_recommendation', 'inputed_book_title')
    op.drop_column('book_recommendation', 'inputed_book_id')
    # ### end Alembic commands ###
